name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:10
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          dnf -y install dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          dnf -y install \
            gcc cmake make \
            zlib-devel bzip2-devel lz4-devel libzstd-devel \
            postgresql-server-devel
      - name: mkdir
        run: mkdir build
        working-directory: ${{ github.workspace }}
      - name: cmake
        run: cmake -DCMAKE_C_FLAGS="-I/usr/include/pgsql" -DCMAKE_BUILD_TYPE=Release ..
        working-directory: ${{ github.workspace }}/build/
      - name: make
        run: make
        working-directory: ${{ github.workspace }}/build/
